### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Vipin1988** [maryamaljanabi/bestbags-nodejs-ecommerce#13]
Hi,
I check this eCommerce code but here some issues coming so you need to describe proper installation guide also so that anybody can setup it on his local system easily and can contribute for this code.
Thanks

**Comment by maryamaljanabi** [comment]
@Vipin1988 Hello, I already added the required information to run the app in the "Run" section of the "ReadMe.md" file. What is missing?

**Comment by liyanda-g** [comment]
hii 
![image](https://user-images.githubusercontent.com/47315701/117650079-e38c1880-b1ad-11eb-9d6f-85f467963627.png)
cant understand
