### ISSUE TITLE
cant find 

### ISSUE THREAD

**Issue by liyanda-g** [maryamaljanabi/bestbags-nodejs-ecommerce#14]
hi , please help to  me to fix 
![image](https://user-images.githubusercontent.com/47315701/117650222-159d7a80-b1ae-11eb-8d98-6c261402f095.png)
i cant fix this were i should give , i have done my try

**Comment by maryamaljanabi** [comment]
@liyanda-g Please read the "RUN" section of the "README.md" file:
_https://github.com/maryamaljanabi/bestbags-nodejs-ecommerce#run_

You must set an env file at the root of the project and supply SESSION_SECRET key.
