### ISSUE TITLE
i have a issue when access link heroku of your 

### ISSUE THREAD

**Issue by dth2k1** [maryamaljanabi/bestbags-nodejs-ecommerce#26]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by maryamaljanabi** [comment]
Hello @dth2k1, the link cannot open at the end of every month because I am using the free plan on Heroku and it usually runs out of Dyno hours during this time of the month. Please wait for the new month and the app should open just fine with you. I will update the ReadMe file about this issue.
