### ISSUE TITLE
Mongodb connect issue

### ISSUE THREAD

**Issue by arjundarkweb** [maryamaljanabi/bestbags-nodejs-ecommerce#36]
Can you please provide a bit brief on how to create .env file and connect mongo db.. if there is any sample.

**Comment by Dheeraj-08** [comment]
If you go through the steps for installation, you will find all the variables there that you need to add in .env file.
Create .env file at root of your application.

**Comment by sreenathkumar** [comment]
@arjundarkweb look

### 1. Create .env inside the root directory:

![image](https://github.com/maryamaljanabi/bestbags-nodejs-ecommerce/assets/60534594/80dbd482-9ee5-43ab-a95e-567844281fa9)

### 2. In the .env file add the credentials:
![image](https://github.com/maryamaljanabi/bestbags-nodejs-ecommerce/assets/60534594/821c6467-e4ae-409c-a228-cd2a2dfc10ba)

**Comment by maryamaljanabi** [comment]
Thanks to everyone who commented. The steps for how to run the project are in the readme file in the [Run](https://github.com/maryamaljanabi/bestbags-nodejs-ecommerce?tab=readme-ov-file#run) section. Please take a look at that. I'm closing the thread.

**Comment by maryamaljanabi** [comment]
Thanks to everyone who commented. The steps for how to run the project are in the readme file in the [Run](https://github.com/maryamaljanabi/bestbags-nodejs-ecommerce?tab=readme-ov-file#run) section. Please take a look at that. I'm closing the thread.
