### ISSUE TITLE
Mongo DB URI Credentials

### ISSUE THREAD

**Issue by adkadle** [maryamaljanabi/bestbags-nodejs-ecommerce#41]
Hi 

How do i provide credentials in the .env file as my Mongo DB requires Authentication

Regards

**Comment by Dheeraj-08** [comment]
1. Login to your MongoDB atlas account.
2. Select Database item from the left menu .
3. Click on Connect option.
4. Select Compass and download it of not already installed.
5. Copt the connection string.
6. Replace <password> with the password you set when user is created on MongoDB
7. Assign the string to MONGO_URI in your .env file

**Comment by maryamaljanabi** [comment]
Thanks for the reply Dheeraj-08. I'm closing the thread since this answer provides all the required information.
