### ISSUE TITLE
I cant able to fill MongoDB Atlas database.

### ISSUE THREAD

**Issue by mohammedThouheedIt** [maryamaljanabi/bestbags-nodejs-ecommerce#44]
I cant able to fill the MongoDB database that you have mentioned to do "you need to navigate to the "seedDB" folder and run "node category-seed.js" and "node products-seed.js" " .
It is showing like this error

![image](https://user-images.githubusercontent.com/120000652/221532175-23e22c54-2a71-4724-b9b9-910141875aae.png)

**Comment by Dheeraj-08** [comment]
Refer the installation steps.
