### ISSUE TITLE
Secret option issue

### ISSUE THREAD

**Issue by elifoz** [maryamaljanabi/bestbags-nodejs-ecommerce#6]
Hi! when I start the app with npm start it returns me that and not upload the website

express-session deprecated undefined resave option; provide resave option node_modules\admin-bro-expressjs\plugin.js:176:14
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules\admin-bro-expressjs\plugin.js:176:14
express-session deprecated req.secret; provide secret option node_modules\admin-bro-expressjs\plugin.js:176:14
express-session deprecated req.secret; provide secret option app.js:34:3

how can I fix it?

**Comment by elifoz** [comment]
> Hi! when I start the app with npm start it returns me that and not upload the website
> 
> express-session deprecated undefined resave option; provide resave option node_modules\admin-bro-expressjs\plugin.js:176:14
> express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules\admin-bro-expressjs\plugin.js:176:14
> express-session deprecated req.secret; provide secret option node_modules\admin-bro-expressjs\plugin.js:176:14
> express-session deprecated req.secret; provide secret option app.js:34:3
> 
> how can I fix it?

okey I fixed that but now when U want to sign in it returns me invalid csrf token
403 error,please help me!

**Comment by elifoz** [comment]
Hi! I want to login as admin but it returns me wrong email and/or password what I should have to do? thanks

**Comment by maryamaljanabi** [comment]
@elifoz Hello, if you want to login as admin in your project, you should provide the following in the .env file:

ADMIN_EMAIL, ADMIN_PASSWORD: the email and password used to log into the admin panel using AdminBro. You can put any email and password here.

ADMIN_COOKIE_NAME, ADMIN_COOKIE_PASSWORD: the cookie name and password used in the AdminBro authentication method. You can put any strings here.

You can use the ADMIN_EMAIL, ADMIN_PASSWORD to login to the admin page.

**Comment by elifoz** [comment]
oket I got it thanks!
