### ISSUE TITLE
.env file is not seen by the other files

### ISSUE THREAD

**Issue by elifoz** [maryamaljanabi/bestbags-nodejs-ecommerce#8]
Hi again! @maryamaljanabi I created a file named .env at the root but when I want to use .env variables I cant.  The other files dont see the variables. Where am I doing mistake

**Comment by maryamaljanabi** [comment]
@elifoz Please post your error message.

**Comment by elifoz** [comment]
for example when I write  secret: process.env.SESSION_SECRET  in app.js the program accept secret undefined

**Comment by maryamaljanabi** [comment]
@elifoz are you sure you installed dotenv package? Because it works just fine for me.

**Comment by maryamaljanabi** [comment]
Closing because this is not an issue with the project.
